version: 2
updates:
  - package-ecosystem: github-actions
    directories:
      - /
      - /.github/workflows
      - /.github/actions/*
      - /.github/actions/setup
    target-branch: main
    schedule:
      interval: monthly
      timezone: America/Detroit
      time: '06:00'
    groups:
      github_actions:
        patterns:
          - '*'

  - package-ecosystem: npm
    directory: /
    target-branch: main
    open-pull-requests-limit: 0
    schedule:
      interval: weekly
      day: sunday
      timezone: America/Detroit
      time: '06:00'
    commit-msessage:
      prefix: 'chore(deps)'
    labels:
      - dependencies
    groups:
      production-deps:
        depedency-type: production
        update-types:
          - minor
          - patch
        patterns:
          - '*'

  - package-ecosystem: npm
    directory: /
    target-branch: 2.x
    open-pull-requests-limit: 0
    schedule:
      interval: weekly
      day: sunday
      timezone: America/Detroit
      time: '06:00'
    commit-message:
      prefix: 'chore(deps)'
    labels:
      - dependencies
    groups:
      production-deps:
        dependency-type: production
        update-types:
          - patch
        patterns:
          - '*'
